# Generated by Django 3.0.7 on 2020-06-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Используемый язык')),
            ],
            options={
                'verbose_name': 'Используемый язык',
                'verbose_name_plural': 'Используемые языки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название проекта')),
                ('task', models.TextField(blank=True, verbose_name='Техническое задание')),
                ('pub_date', models.DateTimeField(null=True, verbose_name='Дата публикации')),
                ('upload', models.FileField(blank=True, upload_to='CompletedProjects/', verbose_name='Готовый проект')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Category', verbose_name='Категория')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Language', verbose_name='Используемый язык')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['category'],
            },
        ),
    ]
