# Generated by Django 3.0.7 on 2020-06-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200613_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='Описание проекта'),
        ),
    ]
