# Generated by Django 3.0.7 on 2020-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20200617_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complited',
            field=models.BooleanField(default=False, verbose_name='Статус выполнения'),
        ),
    ]
